server:
  port: 9090
eureka:
  instance:
    hostname: eureka-center
    appname: registry-center
  client:
    registerWithEureka: false # 单点的时候设置为 false 禁止注册自身
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:9090/eureka
  server:
    enableSelfPreservation: true
    evictionIntervalTimerInMs: 4000